/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bh.view;

import br.com.bh.controller.FinanciamentoController;
import br.com.bh.modelo.dao.ClienteDAO;
import br.com.bh.modelo.dao.FinanciamentoDao;
import br.com.bh.modelo.dao.ParcelasDAO;
import br.com.bh.modelo.entidade.Cliente;
import br.com.bh.modelo.entidade.Financiamento;
import br.com.bh.modelo.entidade.Parcela;
import br.com.bh.utils.Data;
import br.com.bh.utils.Mascara;
import br.com.bh.utils.ValidaCPF;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.java2d.loops.MaskBlit;

/**
 *
 * @author user
 */
public class SimuladorEmprestimo extends javax.swing.JFrame {

   Mascara mask = new Mascara();
    public SimuladorEmprestimo() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTaxa = new javax.swing.JTextField();
        txtValorFinan = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtParcelas = new javax.swing.JTextField();
        txtMargem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbTipoEmprestimo = new javax.swing.JComboBox();
        btnCalcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chkPrice = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        priceTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTotalJurosPrice = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        chkSac = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        sacTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtTotalSac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTotalJurosSac = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        btnContratar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Fax", 0, 13))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setText("Código");

        jLabel2.setText("CPF");

        jLabel4.setText("Valor à Financiar");

        jLabel5.setText("Quantidade de  Parcelas");

        jLabel6.setText("Taxa(%)");

        jLabel7.setText("a.m.");

        jLabel8.setText("Margem Consignada");

        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtTaxa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTaxaKeyTyped(evt);
            }
        });

        txtValorFinan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFinanFocusLost(evt);
            }
        });
        txtValorFinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorFinanActionPerformed(evt);
            }
        });
        txtValorFinan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorFinanKeyTyped(evt);
            }
        });

        txtCpf.setToolTipText("");
        txtCpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("R$");

        txtParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtParcelasKeyTyped(evt);
            }
        });

        txtMargem.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel9.setText("Tipo de Empréstimo");

        cbTipoEmprestimo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antecipado", "Postecipado" }));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calcular.png"))); // NOI18N
        btnCalcular.setText(" CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Data");

        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel10.setText("Contratante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtMargem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtValorFinan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cbTipoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcular))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorFinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtMargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 1, 20)); // NOI18N
        jLabel11.setText("Simular Emprestimo");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PRICE"));

        chkPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPriceActionPerformed(evt);
            }
        });

        priceTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Período", "Juros", "Amortização", "Parcela", "Vencimento", "Saldo Devedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(priceTable);

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel16.setText("R$");

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel17.setText("Total Financiado");

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel18.setText("Juros Pagos");

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel19.setText("R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkPrice)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtTotalJurosPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtTotalJurosPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("SAC"));

        chkSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSacActionPerformed(evt);
            }
        });

        sacTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sacTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Período", "Juros", "Amortização", "Parcela", "Vencimento", "Saldo Devedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(sacTable);

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel14.setText("Total Financiado");

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel15.setText("R$");

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel20.setText("Juros Pagos");

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 1, 13)); // NOI18N
        jLabel21.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkSac)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalJurosSac, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(txtTotalSac)))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkSac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtTotalJurosSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotalSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        sair.setText("SAIR");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        btnContratar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concluir.png"))); // NOI18N
        btnContratar.setText("CONTRATAR");
        btnContratar.setEnabled(false);
        btnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratarActionPerformed(evt);
            }
        });

        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnContratar)
                .addGap(27, 27, 27)
                .addComponent(sair)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContratar)
                    .addComponent(sair))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtValorFinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFinanActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
            voltar();
    }//GEN-LAST:event_voltarActionPerformed

    public void voltar() {
        TelaPrincipal x = new TelaPrincipal();
        x.setVisible(true);
        dispose();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (ValidaCPF.isCPF(txtCpf.getText())) {
            txtCpf.setText(ValidaCPF.imprimeCPF(txtCpf.getText()));
            preencheCliente(txtCpf.getText());
            Date d = new Date();
            Calendar c = new GregorianCalendar();
            c.setTime(d);
            txtData.setText(new SimpleDateFormat("dd/MM/yyyy").format(c.getTime()));
            

        } else {
            JOptionPane.showMessageDialog(null, "O Cpf passado está inválido, digite novamente");
            txtCpf.requestFocus();
            txtCpf.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // valida componentes

        if (txtValorFinan.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "O valor do financiamento deve ser preenchido");
            txtValorFinan.requestFocus();
            return;
        }

        if (txtTaxa.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "A taxa de juros deve ser informada");
            txtTaxa.requestFocus();
            return;
        }

        if (txtParcelas.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "O número de parcelas deve ser informado");
            txtParcelas.requestFocus();
            return;
        }

        double valorFinanciamento = Double.parseDouble(txtValorFinan.getText().replaceAll(",", "."));
        int parcelas = Integer.parseInt(txtParcelas.getText());
        double taxa = Double.parseDouble(txtTaxa.getText());
        preenchePrice(valorFinanciamento, parcelas, taxa);
        preencheSac(valorFinanciamento, parcelas, taxa);
        btnContratar.setEnabled(true);

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtValorFinanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFinanFocusLost
        FinanciamentoController e = new FinanciamentoController();
        txtValorFinan.setText(e.formataNumero(Double.parseDouble(txtValorFinan.getText())));
    }//GEN-LAST:event_txtValorFinanFocusLost

    private void txtValorFinanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorFinanKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorFinanKeyTyped

    private void txtParcelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParcelasKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtParcelasKeyTyped

    private void txtTaxaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxaKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTaxaKeyTyped

    private void btnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarActionPerformed
        FinanciamentoController e = new FinanciamentoController();
        Financiamento financiamento = new Financiamento();
        Cliente c = new Cliente();
        List<Parcela> parcelas = new ArrayList<Parcela>();
        String tipo = "";

        double prestacao1 = 0;
        if (chkPrice.isSelected()) {
            prestacao1 = Double.parseDouble(e.substituiCaractere((priceTable.getValueAt(1, 3).toString()), ",", "."));
            tipo = "PRICE";
        } else {
            if (chkSac.isSelected()) {
                prestacao1 = Double.parseDouble(e.substituiCaractere((sacTable.getValueAt(1, 3).toString()), ",", "."));
                tipo = "SAC";
            } else {
                JOptionPane.showMessageDialog(null, "Uma das tabelas (Price ou SAC) deverá ser selecionada");
                return;
            }

        }

        if (prestacao1 > Double.parseDouble(txtMargem.getText())) {
            JOptionPane.showMessageDialog(null, "A margem é insuficiente para o empréstimo solicitado.  Você pode tentar \n aumentar as prestações ou diminuir o valor total do empréstimo");
            return;
        } else {
            c.setId(Integer.parseInt(txtCodigo.getText()));
            financiamento.setCliente(c);
            financiamento.setQtdParcelas(Integer.parseInt(txtParcelas.getText()));
            financiamento.setTaxa(Double.parseDouble(txtTaxa.getText()));
            financiamento.setTipo(tipo);
            financiamento.setValor(Double.parseDouble((txtValorFinan.getText().replaceAll(",", "."))));
            FinanciamentoDao dao = new FinanciamentoDao();
            ParcelasDAO pdao = new ParcelasDAO();
            financiamento=dao.inserir(financiamento);
           
            for (int linha = 0; linha < sacTable.getModel().getRowCount(); linha++)
                
            {
              Parcela parcela = new Parcela();
              parcela.setFinanciamento(financiamento);
              parcela.setNumeroParcela((int) sacTable.getValueAt(linha, 0));
              parcela.setValor( mask.moneyToDouble(sacTable.getValueAt(linha, 3).toString()));
                try {
                    parcela.setData(Data.formataDataSql(sacTable.getValueAt(linha, 4).toString()) );
                } catch (Exception ex) {
                    Logger.getLogger(SimuladorEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
                }
              parcelas.add(parcela);
            }
            pdao.inserir((ArrayList<Parcela>) parcelas);
            JOptionPane.showMessageDialog(null, "Empréstimo contratado com sucesso");
            voltar();
            
        }


    }//GEN-LAST:event_btnContratarActionPerformed

    private void chkPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPriceActionPerformed
        if (chkPrice.isSelected()) {
            chkSac.setEnabled(false);
            priceTable.setEnabled(true);
            sacTable.setEnabled(false);
        } else {
            chkSac.setEnabled(true);
            priceTable.setEnabled(false);
            sacTable.setEnabled(true);
        }

    }//GEN-LAST:event_chkPriceActionPerformed

    private void chkSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSacActionPerformed
        if (chkSac.isSelected()) {
            chkPrice.setEnabled(false);
        } else {
            chkPrice.setEnabled(true);
        }
    }//GEN-LAST:event_chkSacActionPerformed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
//         if (ValidaCPF.isCPF(txtCpf.getText())) {
//            txtCpf.setText(ValidaCPF.imprimeCPF(txtCpf.getText()));
//            preencheCliente(txtCpf.getText());
//
//        } else {
//            JOptionPane.showMessageDialog(null, "O Cpf passado está inválido, digite novamente");
//            txtCpf.requestFocus();
//            txtCpf.setText("");
//        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void preenchePrice(double valorFinanciamento, int parcelas, double taxa) {
        FinanciamentoController e = new FinanciamentoController();
        DefaultTableModel tTabela = (DefaultTableModel) sacTable.getModel();
        tTabela.setNumRows(0);
        Date d = new Date();
        Calendar c = new GregorianCalendar();
        c.setTime(d);
        double saldoAtual = valorFinanciamento;
        double amortiza = saldoAtual / parcelas;
        double juro = 0;
        double prestacao = 0;
        int j = parcelas;
        double total = 0;
        double totalJuros = 0;
        
        for (int linha = 0; linha <= j; linha++) {
            c.set(Calendar.MONTH, c.get(Calendar.MONTH) + 1);
            if (linha == 0) {
                tTabela.addRow(new Object[]{1});
                sacTable.setValueAt(linha, linha, 0);
                sacTable.setValueAt((juro), linha, 1);
                sacTable.setValueAt(0.0, linha, 2);
                sacTable.setValueAt((prestacao), linha, 3);
                sacTable.setValueAt(e.formataNumero(saldoAtual), linha, 5);

                linha++;
            }
            tTabela.addRow(new Object[]{1});
            juro = e.calculaJuro(saldoAtual, taxa);
            prestacao = amortiza + juro;
            saldoAtual = saldoAtual - amortiza;
            parcelas = parcelas - 1;
            sacTable.setValueAt(linha, linha, 0);
            sacTable.setValueAt(e.formataNumero(juro), linha, 1);
            sacTable.setValueAt(e.formataNumero(amortiza), linha, 2);
            sacTable.setValueAt(e.formataNumero(prestacao), linha, 3);
            sacTable.setValueAt((new SimpleDateFormat("dd/MM/yyyy").format(c.getTime())), linha, 4);
            sacTable.setValueAt(e.formataNumero(saldoAtual), linha, 5);

            total = total + prestacao;
            totalJuros = totalJuros + juro;
            

        }
        txtTotalSac.setText(e.formataNumero(total));
        txtTotalJurosSac.setText(e.formataNumero(totalJuros));

    }

    private void preencheSac(double valorFinanciamento, int parcelas, double taxa) {
        FinanciamentoController e = new FinanciamentoController();
        DefaultTableModel tTabela = (DefaultTableModel) priceTable.getModel();
        tTabela.setNumRows(0);
        Date d = new Date();
        Calendar c = new GregorianCalendar();
        double saldoAtual = valorFinanciamento;
        double amortiza = 0;
        double juro = 0;
        double prestacao = 0;
        int j = parcelas;
        double total = 0;
        double totalJuros = 0;
       
        for (int linha = 0; linha <= j; linha++) {
             c.set(Calendar.MONTH, c.get(Calendar.MONTH) + 1);
            if (linha == 0) {
                tTabela.addRow(new Object[]{1});
                priceTable.setValueAt(linha, linha, 0);
                priceTable.setValueAt((juro), linha, 1);
                priceTable.setValueAt((amortiza), linha, 2);
                priceTable.setValueAt((prestacao), linha, 3);
                priceTable.setValueAt(e.formataNumero(saldoAtual), linha, 4);

                linha++;
            }
            tTabela.addRow(new Object[]{1});
            prestacao = e.calculaPrestacaoPrice(saldoAtual, taxa, parcelas);
            total = total + prestacao;
            juro = e.calculaJuro(saldoAtual, taxa);
            totalJuros = totalJuros + juro;
            amortiza = e.calculaAmortiza(prestacao, juro);
            saldoAtual = e.calculaSaldo(saldoAtual, amortiza);
            parcelas = parcelas - 1;
            priceTable.setValueAt(linha, linha, 0);
            priceTable.setValueAt(e.formataNumero(juro), linha, 1);
            priceTable.setValueAt(e.formataNumero(amortiza), linha, 2);
            priceTable.setValueAt(e.formataNumero(prestacao), linha, 3);
            priceTable.setValueAt((new SimpleDateFormat("dd/MM/yyyy").format(c.getTime())), linha, 4);
            priceTable.setValueAt(e.formataNumero(saldoAtual), linha, 5);

        }
        txtTotal.setText(e.formataNumero(total));
        txtTotalJurosPrice.setText(e.formataNumero(totalJuros));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnContratar;
    private javax.swing.JComboBox cbTipoEmprestimo;
    private javax.swing.JCheckBox chkPrice;
    private javax.swing.JCheckBox chkSac;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable priceTable;
    private javax.swing.JTable sacTable;
    private javax.swing.JButton sair;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtMargem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtParcelas;
    private javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalJurosPrice;
    private javax.swing.JTextField txtTotalJurosSac;
    private javax.swing.JTextField txtTotalSac;
    private javax.swing.JTextField txtValorFinan;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    public void preencheCliente(String cpf) {

        ClienteDAO dao = new ClienteDAO();
        try {

            List<Cliente> clientes = dao.listaCliente(cpf);
            if (clientes.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum cliente com esse cpf");
                txtCpf.requestFocus();
                txtCpf.setText("");
                return;
            }

            Cliente cliente = new Cliente();
            cliente = clientes.get(0);
            txtNome.setText(cliente.getNome());
            txtMargem.setText(String.valueOf(cliente.getMargem()));
            txtCodigo.setText(String.valueOf(cliente.getId()));
            txtCpf.setEditable(false);
            txtCpf.setEnabled(false);
            txtNome.setEnabled(false);
            txtMargem.setEnabled(false);
            btnCalcular.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
